'''
This is a quick and dirty script to build a database of product meta data. In real life this wouldn't
look like this at all, but for the scope of this project I think it is fine.
'''

food_meta_data = [
    {"id": 1, "name": "Apple", "category": "Fruit", "price": 0.5, "availability": True, "shelf_life": "1 Week", "description": "A fresh and juicy apple.", "quantity": 150},
    {"id": 2, "name": "Milk", "category": "Dairy", "price": 2.5, "availability": True, "shelf_life": "5 Days", "description": "A carton of whole milk, rich and creamy.", "quantity": 80},
    {"id": 3, "name": "Chicken Breast", "category": "Meat", "price": 6.99, "availability": True, "shelf_life": "3 Days", "description": "Fresh, boneless chicken breast.", "quantity": 60},
    {"id": 4, "name": "Banana", "category": "Fruit", "price": 0.3, "availability": True, "shelf_life": "1 Week", "description": "A ripe, sweet banana.", "quantity": 200},
    {"id": 5, "name": "Cheddar Cheese", "category": "Dairy", "price": 4.99, "availability": True, "shelf_life": "2 Weeks", "description": "A block of sharp cheddar cheese.", "quantity": 40},
    {"id": 6, "name": "Eggs", "category": "Dairy", "price": 3.49, "availability": True, "shelf_life": "2 Weeks", "description": "A dozen large, free-range eggs.", "quantity": 90},
    {"id": 7, "name": "Ground Beef", "category": "Meat", "price": 7.99, "availability": True, "shelf_life": "3 Days", "description": "Lean ground beef for versatile cooking.", "quantity": 70},
    {"id": 8, "name": "Carrots", "category": "Vegetable", "price": 1.99, "availability": True, "shelf_life": "2 Weeks", "description": "Crunchy, organic carrots.", "quantity": 100},
    {"id": 9, "name": "Orange", "category": "Fruit", "price": 0.8, "availability": True, "shelf_life": "1 Week", "description": "A sweet, juicy orange packed with Vitamin C.", "quantity": 180},
    {"id": 10, "name": "Butter", "category": "Dairy", "price": 4.29, "availability": True, "shelf_life": "3 Weeks", "description": "Creamy, salted butter.", "quantity": 50},
    {"id": 11, "name": "Bread Loaf", "category": "Bakery", "price": 2.99, "availability": True, "shelf_life": "4 Days", "description": "Freshly baked whole grain bread.", "quantity": 120},
    {"id": 12, "name": "Spinach", "category": "Vegetable", "price": 2.5, "availability": True, "shelf_life": "5 Days", "description": "Organic spinach leaves, ready to cook or eat raw.", "quantity": 85},
    {"id": 13, "name": "Salmon Fillet", "category": "Seafood", "price": 9.99, "availability": True, "shelf_life": "3 Days", "description": "Fresh Atlantic salmon fillet.", "quantity": 40},
    {"id": 14, "name": "Yogurt", "category": "Dairy", "price": 1.5, "availability": True, "shelf_life": "2 Weeks", "description": "Creamy Greek yogurt.", "quantity": 100},
    {"id": 15, "name": "Tomato", "category": "Vegetable", "price": 0.99, "availability": True, "shelf_life": "5 Days", "description": "Ripe, red tomatoes perfect for salads or cooking.", "quantity": 160},
    {"id": 16, "name": "Lettuce", "category": "Vegetable", "price": 1.29, "availability": True, "shelf_life": "1 Week", "description": "Fresh, crisp romaine lettuce.", "quantity": 90},
    {"id": 17, "name": "Potato", "category": "Vegetable", "price": 0.6, "availability": True, "shelf_life": "2 Weeks", "description": "Versatile potatoes, great for roasting or mashing.", "quantity": 300},
    {"id": 18, "name": "Strawberries", "category": "Fruit", "price": 3.99, "availability": True, "shelf_life": "5 Days", "description": "Sweet and juicy strawberries.", "quantity": 70},
    {"id": 19, "name": "Pasta", "category": "Pantry", "price": 2.29, "availability": True, "shelf_life": "1 Year", "description": "Classic spaghetti pasta.", "quantity": 150},
    {"id": 20, "name": "Rice", "category": "Pantry", "price": 3.99, "availability": True, "shelf_life": "1 Year", "description": "Long-grain white rice, perfect for side dishes.", "quantity": 100},
    {"id": 21, "name": "Cucumber", "category": "Vegetable", "price": 1.29, "availability": True, "shelf_life": "1 Week", "description": "Cool and crisp cucumber.", "quantity": 120},
    {"id": 22, "name": "Cereal", "category": "Pantry", "price": 4.99, "availability": True, "shelf_life": "6 Months", "description": "Healthy, whole grain breakfast cereal.", "quantity": 80},
    {"id": 23, "name": "Peanut Butter", "category": "Pantry", "price": 3.99, "availability": True, "shelf_life": "6 Months", "description": "Creamy peanut butter with no added sugar.", "quantity": 70},
    {"id": 24, "name": "Grapes", "category": "Fruit", "price": 2.99, "availability": True, "shelf_life": "1 Week", "description": "Seedless green grapes, perfect for snacking.", "quantity": 100},
    {"id": 25, "name": "Honey", "category": "Pantry", "price": 6.49, "availability": True, "shelf_life": "1 Year", "description": "Natural honey, sweet and rich.", "quantity": 50},
    {"id": 26, "name": "Ice Cream", "category": "Frozen", "price": 4.99, "availability": True, "shelf_life": "6 Months", "description": "Rich and creamy vanilla ice cream.", "quantity": 40},
    {"id": 27, "name": "Olive Oil", "category": "Pantry", "price": 8.99, "availability": True, "shelf_life": "1 Year", "description": "Extra virgin olive oil, perfect for cooking and salads.", "quantity": 60},
    {"id": 28, "name": "Orange Juice", "category": "Beverage", "price": 3.99, "availability": True, "shelf_life": "2 Weeks", "description": "Freshly squeezed orange juice.", "quantity": 70},
    {"id": 29, "name": "Sugar", "category": "Pantry", "price": 2.49, "availability": True, "shelf_life": "1 Year", "description": "Granulated white sugar for baking and cooking.", "quantity": 90},
    {"id": 30, "name": "Salt", "category": "Pantry", "price": 1.99, "availability": True, "shelf_life": "1 Year", "description": "Refined table salt, a kitchen essential.", "quantity": 80},
    {"id": 31, "name": "Pepper", "category": "Pantry", "price": 2.99, "availability": True, "shelf_life": "1 Year", "description": "Freshly ground black pepper.", "quantity": 40},
    # Add remaining 49 items
]
food_meta_data.extend([
    {"id": 32, "name": "Avocado", "category": "Fruit", "price": 1.99, "availability": True, "shelf_life": "5 Days", "description": "Creamy and ripe avocados, perfect for guacamole.", "quantity": 60},
    {"id": 33, "name": "Blueberries", "category": "Fruit", "price": 3.99, "availability": True, "shelf_life": "1 Week", "description": "Fresh, antioxidant-rich blueberries.", "quantity": 70},
    {"id": 34, "name": "Bacon", "category": "Meat", "price": 5.49, "availability": True, "shelf_life": "1 Week", "description": "Crispy, smoky bacon strips.", "quantity": 90},
    {"id": 35, "name": "Cabbage", "category": "Vegetable", "price": 1.29, "availability": True, "shelf_life": "2 Weeks", "description": "Fresh and crunchy green cabbage.", "quantity": 40},
    {"id": 36, "name": "Bagels", "category": "Bakery", "price": 3.49, "availability": True, "shelf_life": "4 Days", "description": "Soft and chewy plain bagels.", "quantity": 50},
    {"id": 37, "name": "Zucchini", "category": "Vegetable", "price": 1.49, "availability": True, "shelf_life": "1 Week", "description": "Versatile zucchini, great for grilling or baking.", "quantity": 75},
    {"id": 38, "name": "Whole Wheat Bread", "category": "Bakery", "price": 2.99, "availability": True, "shelf_life": "5 Days", "description": "Freshly baked whole wheat bread.", "quantity": 90},
    {"id": 39, "name": "Muffins", "category": "Bakery", "price": 3.99, "availability": True, "shelf_life": "3 Days", "description": "Moist and fluffy blueberry muffins.", "quantity": 60},
    {"id": 40, "name": "Ground Turkey", "category": "Meat", "price": 6.99, "availability": True, "shelf_life": "3 Days", "description": "Lean ground turkey for healthy meals.", "quantity": 50},
    {"id": 41, "name": "Almond Milk", "category": "Dairy Alternative", "price": 3.99, "availability": True, "shelf_life": "2 Weeks", "description": "Silky smooth unsweetened almond milk.", "quantity": 80},
    {"id": 42, "name": "Sweet Corn", "category": "Vegetable", "price": 0.99, "availability": True, "shelf_life": "1 Week", "description": "Sweet and juicy corn on the cob.", "quantity": 100},
    {"id": 43, "name": "Kale", "category": "Vegetable", "price": 2.49, "availability": True, "shelf_life": "5 Days", "description": "Organic kale leaves, perfect for salads.", "quantity": 70},
    {"id": 44, "name": "Maple Syrup", "category": "Pantry", "price": 7.99, "availability": True, "shelf_life": "1 Year", "description": "Pure Canadian maple syrup.", "quantity": 30},
    {"id": 45, "name": "Coffee Beans", "category": "Beverage", "price": 10.99, "availability": True, "shelf_life": "6 Months", "description": "Freshly roasted coffee beans.", "quantity": 40},
    {"id": 46, "name": "Chocolate Bar", "category": "Snacks", "price": 1.99, "availability": True, "shelf_life": "1 Year", "description": "Rich and creamy milk chocolate bar.", "quantity": 200},
    {"id": 47, "name": "Cashews", "category": "Snacks", "price": 12.99, "availability": True, "shelf_life": "6 Months", "description": "Roasted and salted cashew nuts.", "quantity": 50},
    {"id": 48, "name": "Canned Tuna", "category": "Pantry", "price": 2.79, "availability": True, "shelf_life": "2 Years", "description": "High-quality canned tuna in water.", "quantity": 120},
    {"id": 49, "name": "Frozen Peas", "category": "Frozen", "price": 2.49, "availability": True, "shelf_life": "6 Months", "description": "Sweet and tender frozen peas.", "quantity": 70},
    {"id": 50, "name": "Shrimp", "category": "Seafood", "price": 8.99, "availability": True, "shelf_life": "3 Days", "description": "Fresh, deveined shrimp.", "quantity": 40},
    {"id": 51, "name": "Coconut Water", "category": "Beverage", "price": 2.99, "availability": True, "shelf_life": "2 Weeks", "description": "Hydrating coconut water, naturally sweet.", "quantity": 80},
    {"id": 52, "name": "Lime", "category": "Fruit", "price": 0.39, "availability": True, "shelf_life": "2 Weeks", "description": "Fresh limes, perfect for drinks or seasoning.", "quantity": 120},
    {"id": 53, "name": "Peaches", "category": "Fruit", "price": 2.49, "availability": True, "shelf_life": "1 Week", "description": "Juicy, ripe peaches with a sweet aroma.", "quantity": 90},
    {"id": 54, "name": "Pumpkin", "category": "Vegetable", "price": 3.99, "availability": True, "shelf_life": "3 Weeks", "description": "Fresh pumpkin, ideal for pies or soups.", "quantity": 40},
    {"id": 55, "name": "Cinnamon Rolls", "category": "Bakery", "price": 4.49, "availability": True, "shelf_life": "2 Days", "description": "Warm, gooey cinnamon rolls with icing.", "quantity": 30},
    {"id": 56, "name": "Ham", "category": "Meat", "price": 8.99, "availability": True, "shelf_life": "1 Week", "description": "Savory sliced ham, perfect for sandwiches.", "quantity": 60},
    {"id": 57, "name": "Mozzarella Cheese", "category": "Dairy", "price": 4.49, "availability": True, "shelf_life": "2 Weeks", "description": "Fresh mozzarella cheese, perfect for pizzas.", "quantity": 50},
    {"id": 58, "name": "Oatmeal", "category": "Pantry", "price": 2.99, "availability": True, "shelf_life": "6 Months", "description": "Healthy and hearty rolled oats.", "quantity": 90},
    {"id": 59, "name": "Hot Dogs", "category": "Meat", "price": 3.99, "availability": True, "shelf_life": "5 Days", "description": "Classic beef hot dogs.", "quantity": 80},
    {"id": 60, "name": "Cranberries", "category": "Fruit", "price": 2.99, "availability": True, "shelf_life": "1 Week", "description": "Tart and vibrant cranberries.", "quantity": 40},
    {"id": 61, "name": "Green Tea", "category": "Beverage", "price": 4.99, "availability": True, "shelf_life": "1 Year", "description": "Refreshing and aromatic green tea leaves.", "quantity": 60},
    {"id": 62, "name": "Feta Cheese", "category": "Dairy", "price": 5.49, "availability": True, "shelf_life": "2 Weeks", "description": "Creamy and tangy feta cheese.", "quantity": 30},
    {"id": 63, "name": "Bag of Mixed Nuts", "category": "Snacks", "price": 8.99, "availability": True, "shelf_life": "6 Months", "description": "A healthy mix of roasted nuts.", "quantity": 50},
    {"id": 64, "name": "Watermelon", "category": "Fruit", "price": 6.99, "availability": True, "shelf_life": "1 Week", "description": "Juicy and sweet watermelon.", "quantity": 40},
    {"id": 65, "name": "Frozen Pizza", "category": "Frozen", "price": 7.49, "availability": True, "shelf_life": "6 Months", "description": "Delicious frozen cheese pizza.", "quantity": 60},
    {"id": 66, "name": "Beef Jerky", "category": "Snacks", "price": 5.99, "availability": True, "shelf_life": "6 Months", "description": "Savory and chewy beef jerky.", "quantity": 50},
    {"id": 67, "name": "Red Bell Peppers", "category": "Vegetable", "price": 1.99, "availability": True, "shelf_life": "5 Days", "description": "Crisp and sweet red bell peppers.", "quantity": 90},
    {"id": 68, "name": "Pack of Ramen", "category": "Pantry", "price": 3.99, "availability": True, "shelf_life": "6 Months", "description": "Instant ramen noodles in a variety of flavors.", "quantity": 100},
    {"id": 69, "name": "Pineapple", "category": "Fruit", "price": 4.99, "availability": True, "shelf_life": "1 Week", "description": "Sweet and tangy fresh pineapple.", "quantity": 70},
    {"id": 70, "name": "Bottle of Soda", "category": "Beverage", "price": 1.29, "availability": True, "shelf_life": "6 Months", "description": "Fizzy and refreshing soda in a variety of flavors.", "quantity": 200},
    {"id": 71, "name": "Celery Stalks", "category": "Vegetable", "price": 1.79, "availability": True, "shelf_life": "1 Week", "description": "Crunchy celery stalks, great for snacking.", "quantity": 50},
    {"id": 72, "name": "Frozen Mixed Vegetables", "category": "Frozen", "price": 3.49, "availability": True, "shelf_life": "6 Months", "description": "Convenient frozen mixed vegetables.", "quantity": 80},
    {"id": 73, "name": "Cantaloupe", "category": "Fruit", "price": 2.99, "availability": True, "shelf_life": "1 Week", "description": "Juicy and sweet cantaloupe melon.", "quantity": 40},
    {"id": 74, "name": "Pickles", "category": "Pantry", "price": 4.29, "availability": True, "shelf_life": "6 Months", "description": "Crunchy dill pickles in brine.", "quantity": 50},
    {"id": 75, "name": "Frozen Berries", "category": "Frozen", "price": 5.99, "availability": True, "shelf_life": "6 Months", "description": "A mix of frozen blueberries, strawberries, and raspberries.", "quantity": 60},
    {"id": 76, "name": "Chicken Nuggets", "category": "Frozen", "price": 6.49, "availability": True, "shelf_life": "6 Months", "description": "Crispy and tender frozen chicken nuggets.", "quantity": 70},
    {"id": 77, "name": "Raisins", "category": "Snacks", "price": 2.99, "availability": True, "shelf_life": "1 Year", "description": "Sweet and chewy dried raisins.", "quantity": 80},
    {"id": 78, "name": "Sour Cream", "category": "Dairy", "price": 2.99, "availability": True, "shelf_life": "2 Weeks", "description": "Rich and tangy sour cream.", "quantity": 60},
    {"id": 79, "name": "Bag of Chips", "category": "Snacks", "price": 3.49, "availability": True, "shelf_life": "6 Months", "description": "Crunchy potato chips in a variety of flavors.", "quantity": 150},
    {"id": 80, "name": "Vanilla Almond Granola", "category": "Pantry", "price": 4.99, "availability": True, "shelf_life": "6 Months", "description": "Crunchy granola with vanilla and almonds.", "quantity": 60}
])

pet_meta_data = [
    {"id": 1, "name": "Dog Food - Chicken Recipe", "category": "Food", "price": 20.99, "availability": True, "suitable_for": "Dog", "description": "Nutritious dry dog food with real chicken.", "quantity": 100},
    {"id": 2, "name": "Cat Food - Tuna Flavor", "category": "Food", "price": 15.49, "availability": True, "suitable_for": "Cat", "description": "Delicious wet cat food made with real tuna.", "quantity": 80},
    {"id": 3, "name": "Chew Toy - Bone Shape", "category": "Toys", "price": 7.99, "availability": True, "suitable_for": "Dog", "description": "Durable chew toy in the shape of a bone.", "quantity": 60},
    {"id": 4, "name": "Catnip Mouse Toy", "category": "Toys", "price": 4.99, "availability": True, "suitable_for": "Cat", "description": "Soft mouse toy filled with catnip.", "quantity": 120},
    {"id": 5, "name": "Dog Collar - Blue", "category": "Accessories", "price": 10.49, "availability": True, "suitable_for": "Dog", "description": "Adjustable blue dog collar with a sturdy buckle.", "quantity": 90},
    {"id": 6, "name": "Cat Litter - Scented", "category": "Grooming", "price": 12.99, "availability": True, "suitable_for": "Cat", "description": "Clumping scented cat litter for odor control.", "quantity": 50},
    {"id": 7, "name": "Fish Food - Flakes", "category": "Food", "price": 5.49, "availability": True, "suitable_for": "Fish", "description": "Nutrient-rich fish flakes for tropical fish.", "quantity": 140},
    {"id": 8, "name": "Bird Seed Mix", "category": "Food", "price": 8.99, "availability": True, "suitable_for": "Bird", "description": "Premium seed mix for parrots and other birds.", "quantity": 70},
    {"id": 9, "name": "Reptile Heat Lamp", "category": "Accessories", "price": 19.99, "availability": True, "suitable_for": "Reptile", "description": "Heat lamp for terrariums, ideal for reptiles.", "quantity": 40},
    {"id": 10, "name": "Hamster Wheel", "category": "Toys", "price": 14.99, "availability": True, "suitable_for": "Small Animals", "description": "Silent spinning wheel for hamsters and gerbils.", "quantity": 50},
    {"id": 11, "name": "Dog Leash - Red", "category": "Accessories", "price": 12.49, "availability": True, "suitable_for": "Dog", "description": "Strong and durable red leash for dogs.", "quantity": 100},
    {"id": 12, "name": "Cat Scratching Post", "category": "Toys", "price": 25.99, "availability": True, "suitable_for": "Cat", "description": "Tall scratching post with sisal rope for cats.", "quantity": 30},
    {"id": 13, "name": "Goldfish Bowl", "category": "Accessories", "price": 15.99, "availability": True, "suitable_for": "Fish", "description": "Clear glass bowl perfect for small goldfish.", "quantity": 20},
    {"id": 14, "name": "Dog Bed - Medium", "category": "Accessories", "price": 35.99, "availability": True, "suitable_for": "Dog", "description": "Comfortable and washable medium-sized dog bed.", "quantity": 40},
    {"id": 15, "name": "Reptile Calcium Powder", "category": "Food", "price": 6.99, "availability": True, "suitable_for": "Reptile", "description": "Calcium supplement powder for reptiles.", "quantity": 70},
    {"id": 16, "name": "Bird Perch - Wooden", "category": "Accessories", "price": 10.99, "availability": True, "suitable_for": "Bird", "description": "Wooden perch for parrots and small birds.", "quantity": 60},
    {"id": 17, "name": "Pet Shampoo - Oatmeal", "category": "Grooming", "price": 8.49, "availability": True, "suitable_for": "Dog", "description": "Soothing oatmeal shampoo for pets with sensitive skin.", "quantity": 50},
    {"id": 18, "name": "Cat Carrier", "category": "Accessories", "price": 45.99, "availability": True, "suitable_for": "Cat", "description": "Durable and comfortable carrier for transporting cats.", "quantity": 30},
    {"id": 19, "name": "Hamster Food Pellets", "category": "Food", "price": 6.49, "availability": True, "suitable_for": "Small Animals", "description": "Healthy and balanced food pellets for hamsters.", "quantity": 70},
    {"id": 20, "name": "Aquarium Filter", "category": "Accessories", "price": 29.99, "availability": True, "suitable_for": "Fish", "description": "High-performance filter for freshwater aquariums.", "quantity": 40},
    {"id": 21, "name": "Reptile Tank Thermometer", "category": "Accessories", "price": 9.99, "availability": True, "suitable_for": "Reptile", "description": "Digital thermometer for monitoring tank temperature.", "quantity": 60},
    {"id": 22, "name": "Bird Cage Cleaner", "category": "Grooming", "price": 7.99, "availability": True, "suitable_for": "Bird", "description": "Safe and effective cleaner for bird cages.", "quantity": 50},
    {"id": 23, "name": "Dog Chew Sticks", "category": "Food", "price": 9.49, "availability": True, "suitable_for": "Dog", "description": "Tasty and long-lasting chew sticks for dogs.", "quantity": 80},
    {"id": 24, "name": "Cat Grooming Brush", "category": "Grooming", "price": 11.99, "availability": True, "suitable_for": "Cat", "description": "Soft bristle brush for cats to reduce shedding.", "quantity": 70},
    {"id": 25, "name": "Rabbit Hay Feeder", "category": "Accessories", "price": 18.99, "availability": True, "suitable_for": "Small Animals", "description": "Easy-to-use hay feeder for rabbits.", "quantity": 30},
    {"id": 26, "name": "Dog Sweater - Winter", "category": "Accessories", "price": 19.99, "availability": True, "suitable_for": "Dog", "description": "Cozy winter sweater for small and medium dogs.", "quantity": 40},
    {"id": 27, "name": "Cat Treats - Salmon", "category": "Food", "price": 7.49, "availability": True, "suitable_for": "Cat", "description": "Crunchy salmon-flavored treats for cats.", "quantity": 60},
    {"id": 28, "name": "Hermit Crab Food", "category": "Food", "price": 5.99, "availability": True, "suitable_for": "Reptile", "description": "Nutrient-packed food for hermit crabs.", "quantity": 70},
    {"id": 29, "name": "Dog Toothbrush", "category": "Grooming", "price": 6.49, "availability": True, "suitable_for": "Dog", "description": "Easy-to-use toothbrush for maintaining your dog's oral health.", "quantity": 80},
    {"id": 30, "name": "Reptile Water Dish", "category": "Accessories", "price": 14.99, "availability": True, "suitable_for": "Reptile", "description": "Shallow water dish for reptiles.", "quantity": 50},
    # (Continue with similar details for the remaining 50 items.)
]
pet_meta_data.extend([
    {"id": 31, "name": "Dog Training Pads", "category": "Accessories", "price": 24.99, "availability": True, "suitable_for": "Dog", "description": "Absorbent training pads for house training puppies.", "quantity": 100},
    {"id": 32, "name": "Cat Tree Tower", "category": "Accessories", "price": 99.99, "availability": True, "suitable_for": "Cat", "description": "Multi-level cat tree for climbing, scratching, and napping.", "quantity": 20},
    {"id": 33, "name": "Aquarium Gravel", "category": "Accessories", "price": 8.99, "availability": True, "suitable_for": "Fish", "description": "Decorative gravel for aquarium bases.", "quantity": 60},
    {"id": 34, "name": "Bird Swing Toy", "category": "Toys", "price": 6.49, "availability": True, "suitable_for": "Bird", "description": "Fun and interactive swing toy for birds.", "quantity": 50},
    {"id": 35, "name": "Rabbit Hutch", "category": "Accessories", "price": 120.99, "availability": True, "suitable_for": "Small Animals", "description": "Spacious outdoor rabbit hutch with a built-in run.", "quantity": 15},
    {"id": 36, "name": "Reptile Fogger", "category": "Accessories", "price": 39.99, "availability": True, "suitable_for": "Reptile", "description": "Humidifier and fogger for reptile tanks.", "quantity": 30},
    {"id": 37, "name": "Dog Water Bottle", "category": "Accessories", "price": 14.99, "availability": True, "suitable_for": "Dog", "description": "Portable water bottle for on-the-go hydration.", "quantity": 60},
    {"id": 38, "name": "Cat Laser Pointer Toy", "category": "Toys", "price": 8.49, "availability": True, "suitable_for": "Cat", "description": "Interactive laser pointer toy for endless cat fun.", "quantity": 100},
    {"id": 39, "name": "Parrot Chew Sticks", "category": "Toys", "price": 9.99, "availability": True, "suitable_for": "Bird", "description": "Natural wooden chew sticks for parrots.", "quantity": 70},
    {"id": 40, "name": "Hermit Crab Habitat", "category": "Accessories", "price": 49.99, "availability": True, "suitable_for": "Reptile", "description": "Complete habitat setup for hermit crabs.", "quantity": 25},
    {"id": 41, "name": "Dog Bandana - Holiday", "category": "Accessories", "price": 5.99, "availability": True, "suitable_for": "Dog", "description": "Festive holiday bandana for dogs.", "quantity": 90},
    {"id": 42, "name": "Cat Window Hammock", "category": "Accessories", "price": 29.99, "availability": True, "suitable_for": "Cat", "description": "Space-saving hammock for cats to lounge by the window.", "quantity": 30},
    {"id": 43, "name": "Aquarium Plants - Artificial", "category": "Accessories", "price": 12.49, "availability": True, "suitable_for": "Fish", "description": "Colorful artificial plants for aquariums.", "quantity": 60},
    {"id": 44, "name": "Bird Mirror with Bells", "category": "Toys", "price": 7.99, "availability": True, "suitable_for": "Bird", "description": "Interactive bird mirror with jingling bells.", "quantity": 50},
    {"id": 45, "name": "Small Animal Tunnel", "category": "Toys", "price": 18.99, "availability": True, "suitable_for": "Small Animals", "description": "Collapsible tunnel for rabbits and guinea pigs.", "quantity": 40},
    {"id": 46, "name": "Reptile Rock Shelter", "category": "Accessories", "price": 19.99, "availability": True, "suitable_for": "Reptile", "description": "Natural-looking shelter for reptile enclosures.", "quantity": 30},
    {"id": 47, "name": "Dog Paw Balm", "category": "Grooming", "price": 9.99, "availability": True, "suitable_for": "Dog", "description": "Moisturizing balm for protecting dog paws.", "quantity": 80},
    {"id": 48, "name": "Cat Water Fountain", "category": "Accessories", "price": 39.99, "availability": True, "suitable_for": "Cat", "description": "Automatic water fountain to keep cats hydrated.", "quantity": 20},
    {"id": 49, "name": "Fish Tank Decorations", "category": "Accessories", "price": 15.99, "availability": True, "suitable_for": "Fish", "description": "Decorative ornaments for enhancing fish tanks.", "quantity": 40},
    {"id": 50, "name": "Bird Bath", "category": "Accessories", "price": 22.49, "availability": True, "suitable_for": "Bird", "description": "Durable and spacious bird bath.", "quantity": 25},
    {"id": 51, "name": "Dog Puzzle Toy", "category": "Toys", "price": 16.99, "availability": True, "suitable_for": "Dog", "description": "Interactive puzzle toy to keep dogs entertained.", "quantity": 50},
    {"id": 52, "name": "Cat Calming Spray", "category": "Grooming", "price": 14.99, "availability": True, "suitable_for": "Cat", "description": "Stress-relief spray to calm anxious cats.", "quantity": 30},
    {"id": 53, "name": "Bird Ladder", "category": "Toys", "price": 11.49, "availability": True, "suitable_for": "Bird", "description": "Wooden ladder for climbing and playing.", "quantity": 70},
    {"id": 54, "name": "Small Animal Playpen", "category": "Accessories", "price": 29.99, "availability": True, "suitable_for": "Small Animals", "description": "Portable playpen for rabbits and guinea pigs.", "quantity": 20},
    {"id": 55, "name": "Reptile Spray Bottle", "category": "Accessories", "price": 7.49, "availability": True, "suitable_for": "Reptile", "description": "Misting spray bottle for reptile tanks.", "quantity": 50},
    {"id": 56, "name": "Dog Raincoat - Yellow", "category": "Accessories", "price": 24.99, "availability": True, "suitable_for": "Dog", "description": "Waterproof raincoat for small and medium dogs.", "quantity": 60},
    {"id": 57, "name": "Cat Litter Mat", "category": "Accessories", "price": 18.49, "availability": True, "suitable_for": "Cat", "description": "Non-slip mat to catch litter from cat paws.", "quantity": 40},
    {"id": 58, "name": "Aquarium Heater", "category": "Accessories", "price": 35.99, "availability": True, "suitable_for": "Fish", "description": "Adjustable heater for maintaining tank temperature.", "quantity": 30},
    {"id": 59, "name": "Bird Foraging Toy", "category": "Toys", "price": 14.99, "availability": True, "suitable_for": "Bird", "description": "Interactive foraging toy for parrots and cockatiels.", "quantity": 50},
    {"id": 60, "name": "Rabbit Water Bottle", "category": "Accessories", "price": 9.49, "availability": True, "suitable_for": "Small Animals", "description": "Leak-proof water bottle for rabbits and guinea pigs.", "quantity": 40},
    {"id": 61, "name": "Reptile Habitat Background", "category": "Accessories", "price": 22.99, "availability": True, "suitable_for": "Reptile", "description": "Decorative background for terrariums.", "quantity": 25},
    {"id": 62, "name": "Dog Tennis Balls", "category": "Toys", "price": 7.99, "availability": True, "suitable_for": "Dog", "description": "Durable tennis balls for fetching fun.", "quantity": 100},
    {"id": 63, "name": "Cat Scratcher Board", "category": "Accessories", "price": 12.99, "availability": True, "suitable_for": "Cat", "description": "Cardboard scratcher for satisfying cats' instincts.", "quantity": 80},
    {"id": 64, "name": "Goldfish Food Pellets", "category": "Food", "price": 6.49, "availability": True, "suitable_for": "Fish", "description": "Floating pellets for goldfish nutrition.", "quantity": 60},
    {"id": 65, "name": "Parrot Food - Tropical Blend", "category": "Food", "price": 12.49, "availability": True, "suitable_for": "Bird", "description": "Tropical blend food for parrots.", "quantity": 40},
    {"id": 66, "name": "Rabbit Bedding - Natural", "category": "Accessories", "price": 14.99, "availability": True, "suitable_for": "Small Animals", "description": "Soft and absorbent bedding for rabbits.", "quantity": 30},
    {"id": 67, "name": "Reptile Feeding Tongs", "category": "Accessories", "price": 9.99, "availability": True, "suitable_for": "Reptile", "description": "Precision feeding tongs for reptiles.", "quantity": 60},
    {"id": 68, "name": "Dog Rope Tug Toy", "category": "Toys", "price": 12.49, "availability": True, "suitable_for": "Dog", "description": "Strong rope toy for interactive tugging fun.", "quantity": 70},
    {"id": 69, "name": "Cat Window Perch", "category": "Accessories", "price": 35.99, "availability": True, "suitable_for": "Cat", "description": "Comfortable perch for cats to watch the outside world.", "quantity": 30},
    {"id": 70, "name": "Fish Net", "category": "Accessories", "price": 5.99, "availability": True, "suitable_for": "Fish", "description": "Soft net for handling fish safely.", "quantity": 80},
    {"id": 71, "name": "Bird Cage Stand", "category": "Accessories", "price": 55.99, "availability": True, "suitable_for": "Bird", "description": "Sturdy stand for hanging bird cages.", "quantity": 20},
    {"id": 72, "name": "Small Animal Chew Toys", "category": "Toys", "price": 8.99, "availability": True, "suitable_for": "Small Animals", "description": "Wooden chew toys for healthy teeth.", "quantity": 50},
    {"id": 73, "name": "Reptile Terrarium Kit", "category": "Accessories", "price": 89.99, "availability": True, "suitable_for": "Reptile", "description": "Complete terrarium kit for reptiles.", "quantity": 15},
    {"id": 74, "name": "Dog Bark Collar", "category": "Accessories", "price": 49.99, "availability": True, "suitable_for": "Dog", "description": "Adjustable anti-bark collar for dogs.", "quantity": 25},
    {"id": 75, "name": "Cat Feather Wand", "category": "Toys", "price": 7.49, "availability": True, "suitable_for": "Cat", "description": "Interactive feather wand for cats to chase.", "quantity": 100},
    {"id": 76, "name": "Fish Tank LED Light", "category": "Accessories", "price": 25.99, "availability": True, "suitable_for": "Fish", "description": "Energy-efficient LED light for aquariums.", "quantity": 40},
    {"id": 77, "name": "Bird Cuttlebone", "category": "Food", "price": 4.99, "availability": True, "suitable_for": "Bird", "description": "Essential calcium supplement for birds.", "quantity": 90},
    {"id": 78, "name": "Small Animal Cage Clips", "category": "Accessories", "price": 9.49, "availability": True, "suitable_for": "Small Animals", "description": "Durable cage clips for securing enclosures.", "quantity": 30},
    {"id": 79, "name": "Reptile Waterfall", "category": "Accessories", "price": 49.99, "availability": True, "suitable_for": "Reptile", "description": "Decorative waterfall for enhancing terrarium environments.", "quantity": 20},
    {"id": 80, "name": "Dog Chewing Antler", "category": "Food", "price": 19.99, "availability": True, "suitable_for": "Dog", "description": "Long-lasting natural antler chew for dogs.", "quantity": 70}
])


electronics_meta_data = [
    {"id": 1, "name": "Laptop - 15-inch", "category": "Computers", "price": 899.99, "availability": True, "warranty_period": "1 Year", "description": "A powerful 15-inch laptop with a high-resolution display.", "quantity": 30},
    {"id": 2, "name": "Noise-Cancelling Headphones", "category": "Accessories", "price": 199.99, "availability": True, "warranty_period": "6 Months", "description": "Comfortable over-ear headphones with active noise cancellation.", "quantity": 50},
    {"id": 3, "name": "4K Smart TV", "category": "Home Entertainment", "price": 1199.99, "availability": True, "warranty_period": "2 Years", "description": "Ultra HD 4K smart TV with streaming capabilities.", "quantity": 20},
    {"id": 4, "name": "Smartphone - 128GB", "category": "Phones", "price": 699.99, "availability": True, "warranty_period": "1 Year", "description": "A sleek smartphone with 128GB of storage and a high-quality camera.", "quantity": 40},
    {"id": 5, "name": "Wireless Mouse", "category": "Accessories", "price": 29.99, "availability": True, "warranty_period": "6 Months", "description": "Compact wireless mouse with adjustable DPI settings.", "quantity": 100},
    {"id": 6, "name": "Mechanical Keyboard", "category": "Accessories", "price": 89.99, "availability": True, "warranty_period": "1 Year", "description": "RGB mechanical keyboard with tactile switches.", "quantity": 50},
    {"id": 7, "name": "Gaming Console", "category": "Home Entertainment", "price": 499.99, "availability": True, "warranty_period": "1 Year", "description": "Next-gen gaming console with 4K gaming support.", "quantity": 25},
    {"id": 8, "name": "Bluetooth Speaker", "category": "Accessories", "price": 149.99, "availability": True, "warranty_period": "6 Months", "description": "Portable Bluetooth speaker with deep bass and long battery life.", "quantity": 60},
    {"id": 9, "name": "Webcam - 1080p", "category": "Accessories", "price": 59.99, "availability": True, "warranty_period": "6 Months", "description": "Full HD webcam with a built-in microphone.", "quantity": 70},
    {"id": 10, "name": "External Hard Drive - 2TB", "category": "Storage", "price": 79.99, "availability": True, "warranty_period": "1 Year", "description": "Portable external hard drive with 2TB of storage.", "quantity": 80},
    {"id": 11, "name": "Smartwatch", "category": "Accessories", "price": 249.99, "availability": True, "warranty_period": "1 Year", "description": "Stylish smartwatch with fitness tracking and notifications.", "quantity": 30},
    {"id": 12, "name": "Tablet - 10-inch", "category": "Computers", "price": 399.99, "availability": True, "warranty_period": "1 Year", "description": "Lightweight 10-inch tablet with a vivid display.", "quantity": 40},
    {"id": 13, "name": "Digital Camera", "category": "Cameras", "price": 599.99, "availability": True, "warranty_period": "1 Year", "description": "High-resolution digital camera with advanced features.", "quantity": 25},
    {"id": 14, "name": "USB-C Charger", "category": "Accessories", "price": 19.99, "availability": True, "warranty_period": "6 Months", "description": "Fast-charging USB-C adapter for phones and tablets.", "quantity": 120},
    {"id": 15, "name": "Gaming Headset", "category": "Accessories", "price": 89.99, "availability": True, "warranty_period": "1 Year", "description": "Comfortable gaming headset with surround sound.", "quantity": 60},
    {"id": 16, "name": "Electric Kettle", "category": "Home Appliances", "price": 49.99, "availability": True, "warranty_period": "1 Year", "description": "Quick-boil electric kettle with automatic shutoff.", "quantity": 80},
    {"id": 17, "name": "Portable Power Bank", "category": "Accessories", "price": 34.99, "availability": True, "warranty_period": "6 Months", "description": "High-capacity portable charger for phones and tablets.", "quantity": 90},
    {"id": 18, "name": "Action Camera", "category": "Cameras", "price": 299.99, "availability": True, "warranty_period": "1 Year", "description": "Waterproof action camera with 4K recording.", "quantity": 40},
    {"id": 19, "name": "Fitness Tracker", "category": "Accessories", "price": 99.99, "availability": True, "warranty_period": "1 Year", "description": "Compact fitness tracker with heart rate monitoring.", "quantity": 70},
    {"id": 20, "name": "Home Security Camera", "category": "Cameras", "price": 149.99, "availability": True, "warranty_period": "2 Years", "description": "Wireless home security camera with night vision.", "quantity": 50},
    {"id": 21, "name": "Streaming Media Player", "category": "Home Entertainment", "price": 49.99, "availability": True, "warranty_period": "6 Months", "description": "Compact streaming device for your favorite apps.", "quantity": 100},
    {"id": 22, "name": "Cordless Vacuum", "category": "Home Appliances", "price": 199.99, "availability": True, "warranty_period": "1 Year", "description": "Lightweight cordless vacuum cleaner with powerful suction.", "quantity": 40},
    {"id": 23, "name": "Mini Fridge", "category": "Home Appliances", "price": 129.99, "availability": True, "warranty_period": "2 Years", "description": "Compact mini fridge for beverages and snacks.", "quantity": 25},
    {"id": 24, "name": "Smart Thermostat", "category": "Home Appliances", "price": 249.99, "availability": True, "warranty_period": "1 Year", "description": "Energy-saving smart thermostat with app control.", "quantity": 30},
    {"id": 25, "name": "Coffee Maker", "category": "Home Appliances", "price": 79.99, "availability": True, "warranty_period": "1 Year", "description": "Automatic coffee maker with a programmable timer.", "quantity": 50},
    {"id": 26, "name": "Bluetooth Earbuds", "category": "Accessories", "price": 49.99, "availability": True, "warranty_period": "6 Months", "description": "Wireless earbuds with clear sound and a compact case.", "quantity": 80},
    {"id": 27, "name": "Computer Monitor - 27-inch", "category": "Computers", "price": 299.99, "availability": True, "warranty_period": "2 Years", "description": "Wide-screen 27-inch monitor with ultra-thin bezels.", "quantity": 40},
    {"id": 28, "name": "Smart Doorbell", "category": "Home Appliances", "price": 199.99, "availability": True, "warranty_period": "1 Year", "description": "Smart doorbell with video and motion detection.", "quantity": 20},
    {"id": 29, "name": "Wireless Router", "category": "Accessories", "price": 99.99, "availability": True, "warranty_period": "1 Year", "description": "High-speed wireless router for seamless connectivity.", "quantity": 50},
    {"id": 30, "name": "External SSD - 1TB", "category": "Storage", "price": 149.99, "availability": True, "warranty_period": "1 Year", "description": "Fast and portable external SSD with 1TB capacity.", "quantity": 40},
    # Add remaining 50 items in similar detail.
]

electronics_meta_data.extend([
    {"id": 31, "name": "Tablet Stand", "category": "Accessories", "price": 19.99, "availability": True, "warranty_period": "6 Months", "description": "Adjustable tablet stand for hands-free viewing.", "quantity": 70},
    {"id": 32, "name": "Smart Light Bulb", "category": "Home Appliances", "price": 14.99, "availability": True, "warranty_period": "1 Year", "description": "Energy-efficient smart bulb with app control.", "quantity": 100},
    {"id": 33, "name": "Dash Cam", "category": "Cameras", "price": 129.99, "availability": True, "warranty_period": "1 Year", "description": "Compact dash cam with HD recording and loop function.", "quantity": 50},
    {"id": 34, "name": "Portable Projector", "category": "Home Entertainment", "price": 249.99, "availability": True, "warranty_period": "1 Year", "description": "Portable projector with HDMI support and built-in speaker.", "quantity": 30},
    {"id": 35, "name": "Cordless Hair Clippers", "category": "Accessories", "price": 39.99, "availability": True, "warranty_period": "1 Year", "description": "Cordless hair clippers with adjustable comb settings.", "quantity": 60},
    {"id": 36, "name": "E-Reader - 6-inch", "category": "Computers", "price": 119.99, "availability": True, "warranty_period": "1 Year", "description": "Lightweight e-reader with a glare-free screen.", "quantity": 50},
    {"id": 37, "name": "Electric Toothbrush", "category": "Accessories", "price": 59.99, "availability": True, "warranty_period": "1 Year", "description": "Rechargeable electric toothbrush with multiple cleaning modes.", "quantity": 80},
    {"id": 38, "name": "VR Headset", "category": "Home Entertainment", "price": 399.99, "availability": True, "warranty_period": "1 Year", "description": "Immersive VR headset for gaming and virtual experiences.", "quantity": 20},
    {"id": 39, "name": "Laser Printer", "category": "Computers", "price": 199.99, "availability": True, "warranty_period": "2 Years", "description": "High-speed laser printer with wireless connectivity.", "quantity": 30},
    {"id": 40, "name": "Digital Photo Frame", "category": "Accessories", "price": 99.99, "availability": True, "warranty_period": "1 Year", "description": "Digital photo frame with a bright, vivid display.", "quantity": 40},
    {"id": 41, "name": "Home Theater System", "category": "Home Entertainment", "price": 599.99, "availability": True, "warranty_period": "2 Years", "description": "Premium home theater system with surround sound.", "quantity": 15},
    {"id": 42, "name": "Electric Scooter", "category": "Home Appliances", "price": 349.99, "availability": True, "warranty_period": "1 Year", "description": "Lightweight and foldable electric scooter.", "quantity": 20},
    {"id": 43, "name": "Digital Alarm Clock", "category": "Accessories", "price": 24.99, "availability": True, "warranty_period": "6 Months", "description": "Compact digital alarm clock with a large display.", "quantity": 90},
    {"id": 44, "name": "Wireless Earbuds Case", "category": "Accessories", "price": 15.99, "availability": True, "warranty_period": "6 Months", "description": "Protective case for wireless earbuds.", "quantity": 120},
    {"id": 45, "name": "Robot Vacuum Cleaner", "category": "Home Appliances", "price": 499.99, "availability": True, "warranty_period": "1 Year", "description": "Automatic robot vacuum with app control.", "quantity": 25},
    {"id": 46, "name": "Handheld Fan", "category": "Accessories", "price": 12.99, "availability": True, "warranty_period": "6 Months", "description": "Portable handheld fan with USB charging.", "quantity": 80},
    {"id": 47, "name": "Desktop Speakers", "category": "Accessories", "price": 59.99, "availability": True, "warranty_period": "1 Year", "description": "Compact desktop speakers with rich audio quality.", "quantity": 50},
    {"id": 48, "name": "Gaming Mouse Pad", "category": "Accessories", "price": 14.99, "availability": True, "warranty_period": "6 Months", "description": "Large gaming mouse pad with a smooth surface.", "quantity": 90},
    {"id": 49, "name": "Digital Voice Recorder", "category": "Accessories", "price": 49.99, "availability": True, "warranty_period": "1 Year", "description": "Compact digital voice recorder with long battery life.", "quantity": 30},
    {"id": 50, "name": "Streaming Microphone", "category": "Accessories", "price": 99.99, "availability": True, "warranty_period": "1 Year", "description": "Professional streaming microphone with a USB connection.", "quantity": 40},
    {"id": 51, "name": "Electric Blanket", "category": "Home Appliances", "price": 69.99, "availability": True, "warranty_period": "1 Year", "description": "Soft electric blanket with adjustable heat settings.", "quantity": 60},
    {"id": 52, "name": "HDMI Cable", "category": "Accessories", "price": 9.99, "availability": True, "warranty_period": "6 Months", "description": "High-speed HDMI cable for connecting devices.", "quantity": 150},
    {"id": 53, "name": "Wireless Charger", "category": "Accessories", "price": 29.99, "availability": True, "warranty_period": "1 Year", "description": "Fast wireless charger compatible with most smartphones.", "quantity": 60},
    {"id": 54, "name": "Gaming Chair", "category": "Accessories", "price": 199.99, "availability": True, "warranty_period": "1 Year", "description": "Ergonomic gaming chair with adjustable settings.", "quantity": 30},
    {"id": 55, "name": "Portable Blender", "category": "Home Appliances", "price": 39.99, "availability": True, "warranty_period": "6 Months", "description": "Compact portable blender for smoothies and shakes.", "quantity": 80},
    {"id": 56, "name": "Digital Thermometer", "category": "Accessories", "price": 19.99, "availability": True, "warranty_period": "6 Months", "description": "Accurate digital thermometer with a quick-read display.", "quantity": 120},
    {"id": 57, "name": "Smart Plug", "category": "Home Appliances", "price": 24.99, "availability": True, "warranty_period": "1 Year", "description": "App-controlled smart plug for home automation.", "quantity": 100},
    {"id": 58, "name": "Waterproof Bluetooth Speaker", "category": "Accessories", "price": 89.99, "availability": True, "warranty_period": "1 Year", "description": "Durable waterproof speaker with excellent sound quality.", "quantity": 50},
    {"id": 59, "name": "Portable Fan Heater", "category": "Home Appliances", "price": 49.99, "availability": True, "warranty_period": "1 Year", "description": "Compact fan heater with safety features.", "quantity": 60},
    {"id": 60, "name": "Graphic Tablet", "category": "Computers", "price": 299.99, "availability": True, "warranty_period": "1 Year", "description": "Graphic tablet with a pressure-sensitive stylus.", "quantity": 25},
    {"id": 61, "name": "High-Performance Laptop Cooler", "category": "Accessories", "price": 34.99, "availability": True, "warranty_period": "6 Months", "description": "Laptop cooling pad with silent fans.", "quantity": 80},
    {"id": 62, "name": "Wi-Fi Range Extender", "category": "Accessories", "price": 49.99, "availability": True, "warranty_period": "1 Year", "description": "Device to extend your Wi-Fi range seamlessly.", "quantity": 60},
    {"id": 63, "name": "Noise-Isolating Earbuds", "category": "Accessories", "price": 29.99, "availability": True, "warranty_period": "6 Months", "description": "Compact earbuds with noise-isolating technology.", "quantity": 100},
    {"id": 64, "name": "High-Capacity SD Card - 128GB", "category": "Storage", "price": 39.99, "availability": True, "warranty_period": "1 Year", "description": "Reliable SD card for storage-intensive tasks.", "quantity": 90},
    {"id": 65, "name": "Fitness Smart Scale", "category": "Home Appliances", "price": 79.99, "availability": True, "warranty_period": "1 Year", "description": "Smart scale with weight tracking and app integration.", "quantity": 40},
    {"id": 66, "name": "Premium Laptop Bag", "category": "Accessories", "price": 49.99, "availability": True, "warranty_period": "6 Months", "description": "Durable laptop bag with padded compartments.", "quantity": 70},
    {"id": 67, "name": "Smart Ceiling Fan", "category": "Home Appliances", "price": 249.99, "availability": True, "warranty_period": "2 Years", "description": "Energy-efficient ceiling fan with smart controls.", "quantity": 20},
    {"id": 68, "name": "Electric Pressure Cooker", "category": "Home Appliances", "price": 129.99, "availability": True, "warranty_period": "1 Year", "description": "Multi-functional electric pressure cooker.", "quantity": 30},
    {"id": 69, "name": "Wireless Keyboard", "category": "Accessories", "price": 39.99, "availability": True, "warranty_period": "6 Months", "description": "Sleek wireless keyboard for home and office use.", "quantity": 80},
    {"id": 70, "name": "Portable SSD - 512GB", "category": "Storage", "price": 99.99, "availability": True, "warranty_period": "1 Year", "description": "High-speed portable SSD with 512GB capacity.", "quantity": 50},
    {"id": 71, "name": "Compact Dishwasher", "category": "Home Appliances", "price": 499.99, "availability": True, "warranty_period": "2 Years", "description": "Space-saving compact dishwasher with efficient cleaning.", "quantity": 10},
    {"id": 72, "name": "Soundbar", "category": "Home Entertainment", "price": 199.99, "availability": True, "warranty_period": "1 Year", "description": "Soundbar with immersive sound quality.", "quantity": 20},
    {"id": 73, "name": "Dash Cam Pro", "category": "Cameras", "price": 159.99, "availability": True, "warranty_period": "1 Year", "description": "High-resolution dash cam with advanced features.", "quantity": 40},
    {"id": 74, "name": "Streaming Stick", "category": "Home Entertainment", "price": 39.99, "availability": True, "warranty_period": "6 Months", "description": "Compact streaming stick for easy access to your favorite apps.", "quantity": 80},
    {"id": 75, "name": "Smart Blender", "category": "Home Appliances", "price": 199.99, "availability": True, "warranty_period": "1 Year", "description": "Smart blender with app control for customized recipes.", "quantity": 25},
    {"id": 76, "name": "Gaming Desktop PC", "category": "Computers", "price": 1499.99, "availability": True, "warranty_period": "2 Years", "description": "High-performance gaming desktop with powerful specs.", "quantity": 10},
    {"id": 77, "name": "Smart Coffee Mug", "category": "Accessories", "price": 79.99, "availability": True, "warranty_period": "1 Year", "description": "Temperature-controlled smart coffee mug.", "quantity": 30},
    {"id": 78, "name": "Wireless Gaming Controller", "category": "Accessories", "price": 49.99, "availability": True, "warranty_period": "1 Year", "description": "Ergonomic wireless gaming controller for consoles and PCs.", "quantity": 50},
    {"id": 79, "name": "Laptop Stand", "category": "Accessories", "price": 34.99, "availability": True, "warranty_period": "6 Months", "description": "Adjustable aluminum laptop stand.", "quantity": 60},
    {"id": 80, "name": "Tablet Keyboard", "category": "Accessories", "price": 59.99, "availability": True, "warranty_period": "6 Months", "description": "Bluetooth keyboard for tablets with a lightweight design.", "quantity": 40}
])




ProductMetaData = {
    "food": food_meta_data,
    "pet": pet_meta_data,
    "electronics": electronics_meta_data
}
